### ISSUE TITLE
US #1 : Create Calendar

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#1]
## Value Proposition

**As a** nurse
**I want to** have a calendar
**so that** I can see the days and dates 
​

## Description
![1st wireframe](https://github.com/Katemuya/Capstone-Project/assets/129610930/2c6c48bc-0ba7-4024-b560-c6c23909b4e3)

## Acceptance Criteria
- [ ] A monthly calendar view(default)
- [ ] 7 days a week 
- [ ] The days and dates should be visible

      ​

## Tasks
- [ ] create branch `feature/create calendar`
- [ ] Create calendar Component 
- [ ] Create mock shifts
- [ ] Display mock shifts

**Comment by FelineHuhn** [comment]
Hey Kate, nice first user story 🎉 I love your clear wireframe, in the future you could make the view a little bit more mobile (smartphone), it seems like the middle between mobile and ipad now, but that's not important to adjust for that us. 

I have only some tiny suggestions: 

Acceptance criteria: 
- The formatting of the acceptance criteria seems to be a little bit buggy. 
- You should also mention the headline like: 
   - the headline is "My Calendar"
- maybe you could describe the calendar more in a way like: 
   - a calendar in a monthly view with 7 days a week is displayed
   - the weekdays and dates are displayed in the calendar
   
Tasks: 
- a better branch name could be only feature/calendar, or?
- "use the `Calendar` component to display a calendar" could be enough instead of mentioning functions, or?

**Comment by Katemuya** [comment]
Thank you for the review and suggestions Feline,
I will work on the mobile view for the next wireframes and edit the US for the immediate changes.

**Comment by RonnySteady** [comment]
Hey Kate, looks really good to me 👍 Maybe you can write all of your new components (Time, WeeklyCalendar) in backticks `ComponentName` to make the  it more visible.

**Comment by mbosselmann** [comment]
Hey Kate,
great job! I really like this user story. :) I only have two remarks for you:
- You could add in your wireframe a legend that tells which color belongs to each shift. This could help the user to get an overview. :)
- Something went wrong in the formatting of your acceptance criteria. There are empty lines between each criterion and there is an empty codeblock that is not needed. Please check. :)

Everything else looks fine, but I like Ronald's remark too to use backticks for component names :)

**Comment by Katemuya** [comment]
Hi Mareike and Ronald,
Thank you for the feedback and suggestions. I have made the adjustments as you advised.
