### ISSUE TITLE
Create Delete Button

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#10]
## Value Proposition

**As a** user
**I want to** be able to delete my shifts
**in order to** remove previously edited shift information
​

## Description
![Screenshot 2023-06-29 at 11 05 19](https://github.com/Katemuya/Capstone-Project/assets/129610930/5fe1870a-c39d-495c-b560-659ddf010143)

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria
- [ ] A delete button is displayed on the edit shift dialogue
- [ ] Clicking on the button removes the previously edited information

## Tasks
- [ ] Create branch `feature/delete`
- [ ] Create ` DeleteButton` Component
- [ ] render the ` DeleteButton` Component in the `Dialog` Component

**Comment by actyvystom** [comment]
Hey Kate, took me some time to understand the difference to [US6](https://github.com/Katemuya/Capstone-Project/issues/9)... 
I assume that this one is meant for deletion of already saved shifts?  
So I suggest the following changes: 
- Change the title to Delete saved shifts
- Adjust your value proposition accordingly, e.g.
> As a user
> I want to be able to delete shifts from my plan 
> in order to remove shifts which have been saved incorrectly or have been replaced
- Add some more detail to your task list and also describe what needs to be done to implement the delete functionality
- Think of a way to confirm the deletion (as it is a destructive functionality)
- Adjust your acceptance criteria accordingly and add more detail to the deletion process

Cheers, Thomas

**Comment by Katemuya** [comment]
Hi Thomas,
thank you for the review and suggestions. Before I had the idea of just deleting the edited shifts but after your question I decided to give the user the option to delete and add shifts. I have updated the US as advised. 
kind regards :)
