### ISSUE TITLE
Choosing Colour Option

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#11]
## Value Proposition

**As a** nurse
**I want to**  colour code my shifts  
**in order to** have an easier and clearer view of all my shifts 
​

## Description
![Screenshot 2023-06-29 at 11 48 06](https://github.com/Katemuya/Capstone-Project/assets/129610930/c79d66a3-3210-4c87-a24c-f54416fc37cf)
​
## Acceptance Criteria
- [ ] A background colour selector is displayed 
- [ ] Clicking on one colour updates the respective shift colour 
- [ ] Once the dialogue is saved the shifts overview shows the chosen colour
      ​

## Tasks
- [ ] Create branch `feature/BackgroundColour`
- [ ] Create `BackgroundColour` Component
- [ ]Apply minimal styling to display the colours
- [ ] Add `Background Colour` component to  the `Dialogue` component
- [ ] Link the `BackgroundColour` to the shifts overview page to update the colours after getting saved

**Comment by Danielschuetzle** [comment]
LGTM 👍🏻
