### ISSUE TITLE
Create New Shifts

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#15]
## Value Proposition

**As a** nurse 
**I want to** be able to create new shifts
**in order to**have them on my pre-defined shifts list 
​

## Description
<img width="685" alt="Screenshot 2023-07-06 at 12 45 34" src="https://github.com/Katemuya/Capstone-Project/assets/129610930/e0a7ee1e-d425-4afe-94e2-f5219f4da11c">

## Acceptance Criteria

- [ ] A create shift button is displayed on the shifts Page
- [ ] clicking on the button opens a dialogue with a form
- [ ] The form has shift Name, start and end input fields
- [ ] The form also has a Add shift button
- [ ] Clicking on "Add Shift" button updates the shifts list and closes the dialogue
      ​

## Tasks
- [ ] create branch `feature/create shifts`
- [ ] create `NewShifts` Components
- [ ] Create a "Add Shift" button
- [ ] Update the `ShiftsOverview` component to display the `NewShifts` Component
