### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#17]
## Value Proposition

**As a** user
**I want to** have a navigation bar
**so that/in order to** I can easily move from page to page
​

## Description
![Screenshot 2023-07-10 at 14 22 03](https://github.com/Katemuya/Capstone-Project/assets/129610930/5d9a59cb-0246-41d0-b5c8-133e6d32a6e5)

## Acceptance Criteria

- [ ] A navigation bar is displayed at the bottom of the page
- [ ] "calendar" and "shifts" are to be seen in the navigation bar
- [ ] When clicked, they lead to the respective pages
      ​

## Tasks
- [ ] create branch feature/NavigationBar
- [ ] create component `NavigationBar`
- [ ] use the Calendar and ShiftsPage Links
- [ ] Use styled components to style the component
