### ISSUE TITLE
Monthly Calendar

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#2]
## Value Proposition

**As a** nurse
**I want to** have a monthly calendar
**so that I** can have a monthly overview of my shifts  
​

## Description
![US2 Wireframe](https://github.com/Katemuya/Capstone-Project/assets/129610930/c1f830c6-ecd2-49ea-84e8-7f569d61d1fd)

## Acceptance Criteria

- [ ] A monthly calendar with 31 days is displayed
- [ ] The weekdays and dates are displayed 
- [ ] Mock shifts are displayed
- [ ] Month name and year are displayed above the calendar
- [ ] A button with the month, week and day view options is displayed
      ​

## Tasks

- [ ] create branch feature/MonthlyCalendar
- [ ] Create a `MonthlyCalendar`   Component
- [ ] Use the `MonthlyCalendar` component to display the monthly view.
- [ ] Create a `Button` Component that will display the three buttons used to switch the calendar into different views(Week, Month Day)
- [ ] Display the mocks shifts on the monthly view calendar

**Comment by MariaRiosNavarro** [comment]
I don't recognise very well in your Wireframe if it is a single button or 3 different buttons for each of the views. Maybe you can write above that it is a slide button or describe it. Thanks

**Comment by Katemuya** [comment]
Thank you for the feedback and suggestion. I have updated it.
