### ISSUE TITLE
Shifts Page

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#3]
## Value Proposition

**As a** user 
**I want to** to be able to predefine my shifts 
**so that** I can easily edit them later
​

## Description
![US3 Wireframe](https://github.com/Katemuya/Capstone-Project/assets/129610930/3046a939-8fbf-46c8-8f2f-9620be82f40b)

## Acceptance Criteria
- [ ] The title "shifts" is displayed
- [ ] The sub-title "schedule" is displayed
- [ ] Entry fields to set shift name,  shift start time and end time are displayed
- [ ] A "save" Button is displayed
- [ ] A link named "Back" used to navigate to "My Calendar" is displayed
      ​
## Tasks
- [ ] Create branch `feature/shifts`
- [ ] Create `Shifts` Component
- [ ] Create a shifts page to display the `Shifts ` component
- [ ] Create the entry fields;Shift Name, Start, End 
- [ ] create a button to save the input data from the input fields
- [ ] Link the shifts page to "My Calendar" using the `Link` Component

**Comment by MichanNan** [comment]
LGTM 🚀

**Comment by TmWgnr** [comment]
hey Kate,
i think its a good scope.
Just one suggestions for ur Value Proposition:

As a user
I want to to be able to predefine my shifts
so that I can save it in ( i dont know where exactly u gonna save it) my shift plan.

because in this user story you dont create a page where u can edit shifts.

cheers:)
