### ISSUE TITLE
Shifts Page

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#4]
## Value Proposition

**As a** user 
**I want to** have an overview page with all the shifts I have already predefined
**so that** I can see them all in one page
​

## Description
![US3 wireframe](https://github.com/Katemuya/Capstone-Project/assets/129610930/61b4102a-e295-46fe-b900-84354ea95c3f)

​

## Acceptance Criteria

- [ ] The title "My Shifts" is displayed
- [ ] a list of predefined shifts is displayed
- [ ] The shift duration is displayed under the shifts
- [ ] A button "edit" is displayed next to each shift item
- [ ] Clicking on the "edit" button leads to the shift page 
- [ ] A navigation Link named "Back" is displayed. 
- [ ] Clicking on "Back" leads to "My Calendar"
      ​

## Tasks

- [ ] Create branch `feature/shifts`
- [ ] Create `Shifts` Component
- [ ] Create the page `pages/shifts/index` that renders the `Shifts` Component
- [ ] Create the edit button
- [ ] Link the shifts page to "My Calendar" using the `Link` Component named "Back"

**Comment by RonnySteady** [comment]
Hi Kate, good user story but I think the value proposition is quite short (list with predefined shifts)   compared to the acceptance criteria and tasks (edit and back buttons). Maybe you should add that details in the value proposition or make a separate user story for the edit and back button. Cheers, Ronald.

**Comment by nastiche** [comment]
L*very*GTM!
