### ISSUE TITLE
Add delete Button in events

### ISSUE THREAD

**Issue by Katemuya** [Katemuya/Capstone-Project#9]
## Value Proposition

**As a** user
**I want to** be able to delete my shifts
**in order to** remove previously edited shift information
​

## Description
![Screenshot 2023-06-29 at 11 13 32](https://github.com/Katemuya/Capstone-Project/assets/129610930/05d47eae-d668-416c-acc5-b3be499eec4e)

## Acceptance Criteria
- [ ] A delete button is displayed on the add event dialogue
- [ ] Clicking on the button removes the previously edited information

## Tasks
- [ ] Create branch `feature/delete`
- [ ] Create ` DeleteButton` Component
- [ ] render the ` DeleteButton` Component in the `CreateEvent` Component

**Comment by actyvystom** [comment]
A nice one! 🚀

**Comment by actyvystom** [comment]
After reviewing US7, I guess this should be changed, too. 
I assume that this one is more about cancelling the creation of a shift? So I would suggest to change all wordings from delete to cancel and describe in more detail the functionality of cancelling the shift creation in your task list and your acceptance criteria...
Cheers, Thomas

**Comment by Airglow98** [comment]
lgtm :)
